### PR TITLE
Simple TKinter frontend for kodi-cli

### PR DESCRIPTION
**Pull request by elpraga**
To make it easier to use in X-window and to give some visual response.

### CODE REVIEW

**Comment by elpraga** [comment]
If you have xclip installed, it automatically puts your selection to the input window. I wrote an eartlier version in YAD, but it would require that people first download and compile YAD, and I thought it would be too much to ask. It also doesn't require installing any additional python libraries.

**Comment by nawar** [comment]
Awesome! Thanks, I'll merge your work into a separate branch for anyone wants to a frontend for kodi-cli. However, there are conflicts that need to be resolved first, will you be able to do it?

**Comment by elpraga** [comment]
I'll have to have a look. I didn't realize it would appear directly on your account, but if you like it, cool! :smile: I'll also have to add a simple install.sh, as the version that plays nicely with Wayland requires a `.desktop` file present.

I'll check the conflicts when I have a moment..

**Comment by elpraga** [comment]
Now it should be fine, but you might want to erase some of my notes. I do prefer to keep them there in my branch, just in case I need to loop up something about kodi again.

In any case, i didn't make any changes to `kodi-cli` this time.

**Comment by elpraga** [comment]
You might want to change the name of the branch. It is now a GTK3 frontend. I haven't touched the TKinter one in ages

**Comment by nawar** [comment]
Okay, I'll do that. Thanks a lot 👍

**Comment by elpraga** [comment]
Thank you! :wink: :+1:

**Pull request merged**
